name: Coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Coverage
      run: |
        npm ci
        npm run test-cov
        exit 0
